name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # API key is pulled from GitHub Secrets
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Cache Gradle
        uses: gradle/gradle-build-action@v3

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build Debug
        run: ./gradlew assembleDebug --stacktrace -POPENAI_API_KEY="${OPENAI_API_KEY}"

      - name: Run Lint
        run: ./gradlew lint -POPENAI_API_KEY="${OPENAI_API_KEY}"

      - name: Run Unit Tests
        run: ./gradlew test -POPENAI_API_KEY="${OPENAI_API_KEY}"

      - name: Policy & Static Checks
        run: ./gradlew check -POPENAI_API_KEY="${OPENAI_API_KEY}"