name: SDK Auto-Bump

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35"

      - name: Run bump script
        run: ./tools/bump_sdk.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: bump target/compile SDK to latest"
          title: "SDK Auto-Bump"
          body: "Automated bump of targetSdk and compileSdk."
          branch: "auto/sdk-bump"
          base: "main"